name: weather_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  skeletonizer: ^2.0.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  sqflite: ^2.4.2
  path: ^1.9.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: UbuntuCondensed
      fonts:
        - asset: assets/fonts/UbuntuCondensed-Regular.ttf
          weight: 400